### ISSUE TITLE
来支持一下

### ISSUE THREAD

**Issue by cmdedj** [peterli110/pcrdfans.com#1]
pcr玩家给你点赞

**Comment by peterli110** [comment]
> pcr玩家给你点赞

噗，issue别当评论区用啊

**Comment by cmdedj** [comment]
> > pcr玩家给你点赞
> 
> 噗，issue别当评论区用啊

没地方评论啊

**Comment by cmdedj** [comment]
> > pcr玩家给你点赞
> 
> 噗，issue别当评论区用啊

要不开一个专门的issue当评论去吧
