### ISSUE TITLE
dalao您好,bot食用链接在哪?站内找不到bot文档链接.

### ISSUE THREAD

**Issue by KashimuraBaka** [peterli110/pcrdfans.com#11]
申请了APIKey之后,使用bot尝试请求,但是返回的是102错误.
想找文档寻求解决办法,文档找不到blog也挂了（ ° ͜ ʖ °）????

**Comment by peterli110** [comment]
我没写文档，你可以参考一下https://github.com/Ice-Cirno/HoshinoBot

**Comment by KashimuraBaka** [comment]
谢谢!已找到问题
