### ISSUE TITLE
闇シズルの専用１追加漏れ

### ISSUE THREAD

**Issue by soniczwei** [peterli110/pcrdfans.com#42]
![图片](https://github.com/peterli110/pcrdfans.com/assets/165942437/f22149b3-59e2-492e-8eeb-0e9b539bffec)

**Comment by peterli110** [comment]
> ![图片](https://private-user-images.githubusercontent.com/165942437/319297068-f22149b3-59e2-492e-8eeb-0e9b539bffec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyNDE4MDYsIm5iZiI6MTcxMjI0MTUwNiwicGF0aCI6Ii8xNjU5NDI0MzcvMzE5Mjk3MDY4LWYyMjE0OWIzLTU5ZTItNDkyZS04ZWViLTBlOWI1MzliZmZlYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNFQxNDM4MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MjA1MjU3YjQ2YTQ5ZjkzOGE5MTYxNTY0MmMyYjI1NzdhYjM3ODZkMjljNjU4ZjE5NWNiNWIzY2ExNTY4MWRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9j1HipFO8RVKlRS-PeXfcrPPnTQtL7vVwwUrASPs21I)

Thank you. It's a bug and I just fixed it
ありがとうございます。 それはバグなので修正しました
