### ISSUE TITLE
pcrdfans的作者请求一个,想为机器人申请一个API接口....

### ISSUE THREAD

**Issue by KuonType** [peterli110/pcrdfans.com#5]
十分感谢大大做出这么好的系统....希望可以申请调用一个接口万分感谢!
站内昵称:十眼鬼姬

**Comment by YazawaKazusa** [comment]
为什么不试着让dalao更新网站？然后自己克隆一份挂在内网然后调用呢？

**Comment by KuonType** [comment]
> 为什么不试着让dalao更新网站？然后自己克隆一份挂在内网然后调用呢？

因为很多jjc解法是玩家自主提供的。。。大部分的解法需要玩家自己来整理，dalao的网站做了资源收集，所以主要想依靠一下大佬的接口。。。只有自己的2个群在使用所以量不会很大，也可以赞助服务器。。。。

**Comment by peterli110** [comment]
https://www.pcrdfans.com/bot 更新了
