### ISSUE TITLE
请问如何获取Pcrdfans API？

### ISSUE THREAD

**Issue by Glorybow** [peterli110/pcrdfans.com#6]
如果站长大佬能够私信一个给我，感激不尽，邮箱是Glorybow#vip.qq.com。#换成@。祝生活愉快！

**Comment by Blokura** [comment]
网站首页有申请入口，QQBot联动

**Comment by Glorybow** [comment]
> 网站首页有申请入口，QQBot联动

感谢回复，已经提交申请

**Comment by RicardoCZ** [comment]
请问提交完申请后从哪获得回复

**Comment by peterli110** [comment]
> 请问提交完申请后从哪获得回复

我有空了就会看看，刷新就有了
