### ISSUE TITLE
大佬你好，我想给两个群申请api可以吗

### ISSUE THREAD

**Issue by littlesixsky** [peterli110/pcrdfans.com#7]
搭建了咖啡大佬的yobot，给自己和朋友的工会使用，想给两个群弄一个jjc查询，请问我可以申请一个两个群用的api吗，谢谢大佬

**Comment by peterli110** [comment]
https://www.pcrdfans.com/bot 在这填一下就行

**Comment by littlesixsky** [comment]
> https://www.pcrdfans.com/bot 在这填一下就行

谢谢大佬，之前我只用了一个QQ群号来申请，两个群都能用，问题解决了，API是一个人服务器或者IP来判断的吧？

**Comment by peterli110** [comment]
> > https://www.pcrdfans.com/bot 在这填一下就行
> 
> 谢谢大佬，之前我只用了一个QQ群号来申请，两个群都能用，问题解决了，API是一个人服务器或者IP来判断的吧？

是ip，群号就是留个记录方便统计
